package TestApp;


/**
* TestApp/TestOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./TestApp.idl
* Thursday, 14 May 2026 12:52:51 o'clock IST
*/

public interface TestOperations 
{
  void m ();
} // interface TestOperations
